// @TODO add other levels and collectables
const blueprint = `
..........
....0.....
....0000..
.......0..
....0..0..
..........
.......0..
.....0....
..0.......
.....x.0..
`
export const levelList = [blueprint]
