// @TODO add other levels and collectables
const blueprint = `
x.........
....0.....
....0000..
.......0..
....0..0..
..........
.......0..
.....0....
..0.......
.......0..
`
export const levelList = [blueprint]
